/**
 * Research Post OG Data
 * Auto-generated by scripts/generate-research-og-data.js
 * DO NOT EDIT MANUALLY
 *
 * Generated: 2025-12-30T23:14:06.599Z
 * Total posts: 100
 */

export const RESEARCH_OG_DATA = {
  "48": {
    "title": "Weekly Media Recap #48",
    "description": "Bitcoin, as covered in the mainstream media.",
    "image": "https://cms.perception.to/content/images/2024/06/Blue-White-Gradient-Instagram--2--2.png",
    "publishedAt": "2024-06-24T15:00:15.000+02:00",
    "updatedAt": "2024-06-24T15:00:16.000+02:00",
    "author": "BTCP Staff",
    "tags": [
      "Weekly Digest",
      "#Import 2025-12-30 07:22"
    ]
  },
  "test": {
    "title": "🔥 test",
    "description": "🔥",
    "image": "https://perception-og-image.fernandonikolic.workers.dev/api/og-image?title=%F0%9F%94%A5+test&description=%F0%9F%94%A5+&theme=dark",
    "publishedAt": "2025-12-30T09:45:00.000+01:00",
    "updatedAt": "2025-12-30T09:45:00.000+01:00",
    "author": "Fernando Nikolic",
    "tags": []
  },
  "the-6-7x-mainstream-media-coverage-gap-q3-report": {
    "title": "The 6.7x mainstream media coverage gap (Q3 Report)",
    "description": "Elite outlets published 3% of Bitcoin coverage in Q3",
    "image": "https://cms.perception.to/content/images/2025/10/Q3-2025-REPORT-HIDDEN-IN-PLAIN-SIGHT--1-.png",
    "publishedAt": "2025-10-17T15:05:01.000+02:00",
    "updatedAt": "2025-10-17T15:05:00.000+02:00",
    "author": "Fernando Nikolic",
    "tags": [
      "Reports",
      "#Import 2025-12-30 07:22"
    ]
  },
  "perception-quarterly-hidden-in-plain-sight": {
    "title": "📈 Perception Quarterly: Hidden In Plain Sight",
    "description": "The 2,948-to-1 intelligence gap revealed.",
    "image": "https://cms.perception.to/content/images/2025/10/Q3-2025-REPORT-HIDDEN-IN-PLAIN-SIGHT.png",
    "publishedAt": "2025-10-02T14:26:11.000+02:00",
    "updatedAt": "2025-10-17T01:17:15.000+02:00",
    "author": "Fernando Nikolic",
    "tags": [
      "Reports",
      "#Import 2025-12-30 07:22"
    ]
  },
  "why-i-just-left-my-vp-job-to-build-in-the-chaos": {
    "title": "Why I just left my VP job to build in the chaos",
    "description": "I'm going all-in on Perception.",
    "image": "https://images.unsplash.com/photo-1636146950751-3e5dc5fe1273?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMTc3M3wwfDF8c2VhcmNofDV8fGV4aXQlMjBzaWdufGVufDB8fHx8MTc1NDE2ODMyNXww&ixlib=rb-4.1.0&q=80&w=2000",
    "publishedAt": "2025-08-02T23:06:27.000+02:00",
    "updatedAt": "2025-08-02T23:06:27.000+02:00",
    "author": "Fernando Nikolic",
    "tags": [
      "Opinion",
      "#Import 2025-12-30 07:22"
    ]
  },
  "q2-2025-crypto-media-bitcoin-coverage-report": {
    "title": "Q2 2025 Crypto Media Bitcoin Coverage Report",
    "description": "Executive Summary Crypto-native media's Bitcoin coverage in Q2 2025 reveals a strikingly different narrative from mainstream outlets. Across 2,695 articles...",
    "image": "https://cms.perception.to/content/images/2025/07/Q1-Legacy-media-report--1-.png",
    "publishedAt": "2025-07-14T14:31:41.000+02:00",
    "updatedAt": "2025-10-01T02:30:59.000+02:00",
    "author": "BTCP Staff",
    "tags": [
      "Reports",
      "#Import 2025-12-30 07:22"
    ]
  },
  "q2-2025-mainstream-media-bitcoin-coverage-report": {
    "title": "Q2 2025 Mainstream Media Bitcoin Coverage Report",
    "description": "Executive Summary Mainstream media coverage of Bitcoin in Q2 2025 revealed a deeply polarized narrative landscape, with 1,116 articles published across 18 m...",
    "image": "https://cms.perception.to/content/images/2025/07/Q1-Legacy-media-report.png",
    "publishedAt": "2025-07-08T15:31:12.000+02:00",
    "updatedAt": "2025-07-08T15:31:12.000+02:00",
    "author": "BTCP Staff",
    "tags": [
      "Reports",
      "#Import 2025-12-30 07:22"
    ]
  },
  "these-outlets-shaped-bitcoins-narrative-in-may": {
    "title": "These Outlets Shaped Bitcoin’s Narrative in May.",
    "description": "The Bitcoin Mainstream Media Power Rankings — May 2025 Edition",
    "image": "https://cms.perception.to/content/images/2025/06/May-2025Legacy-media-report.png",
    "publishedAt": "2025-06-09T16:33:40.000+02:00",
    "updatedAt": "2025-06-09T16:33:40.000+02:00",
    "author": "Fernando Nikolic",
    "tags": [
      "Reports",
      "#Import 2025-12-30 07:22"
    ]
  },
  "about-the-fts-bitcoin-coverage": {
    "title": "About the FT’s Bitcoin Coverage",
    "description": "Dear reader, The Financial Times just hit its 400th piece on Bitcoin since 2018 with a banger of a mini-documentary featuring Michael Saylor that went viral...",
    "image": "https://cms.perception.to/content/images/2025/05/maxresdefault.jpg",
    "publishedAt": "2025-05-15T14:53:54.000+02:00",
    "updatedAt": "2025-05-15T14:53:54.000+02:00",
    "author": "Fernando Nikolic",
    "tags": [
      "Reports",
      "#Import 2025-12-30 07:22"
    ]
  },
  "q1-2025-mainstream-media-bitcoin-coverage-report": {
    "title": "Q1 2025 Mainstream Media Bitcoin Coverage Report",
    "description": "Prepared for Capital Allocators, CIOs, and Institutional Strategists",
    "image": "https://cms.perception.to/content/images/2025/05/Q1-Legacy-media-report.png",
    "publishedAt": "2025-05-01T16:15:15.000+02:00",
    "updatedAt": "2025-05-01T16:15:14.000+02:00",
    "author": "Fernando Nikolic",
    "tags": [
      "Reports",
      "#Import 2025-12-30 07:22"
    ]
  },
  "crypto-media-sentiment-exposed-whos-bullish-on-bitcoin": {
    "title": "Crypto Media Sentiment Exposed: Who’s Bullish on Bitcoin?",
    "description": "Crypto Media Bitcoin Sentiment Report – Q1 2025",
    "image": "https://cms.perception.to/content/images/2025/04/Q1-Crypto-media-report.png",
    "publishedAt": "2025-04-21T15:36:45.000+02:00",
    "updatedAt": "2025-04-21T15:36:45.000+02:00",
    "author": "Fernando Nikolic",
    "tags": [
      "Reports",
      "#Import 2025-12-30 07:22"
    ]
  },
  "q1-2025-bitcoin-narrative-intelligence-brief-what-institutions-missed-after-100k": {
    "title": "Q1 2025 Bitcoin Narrative Intelligence Brief – What Institutions Mi...",
    "description": "Narrative Trends, Sentiment Shifts & Institutional Signals",
    "image": "https://cms.perception.to/content/images/2025/04/Q1-Report.png",
    "publishedAt": "2025-04-07T14:03:34.000+02:00",
    "updatedAt": "2025-04-07T14:03:33.000+02:00",
    "author": "Fernando Nikolic",
    "tags": [
      "#Import 2025-12-30 07:22"
    ]
  },
  "why-most-fear-greed-indexes-misread-bitcoin-sentiment": {
    "title": "Why Most Fear & Greed Indexes Misread Bitcoin Sentiment",
    "description": "Bitcoin’s market sentiment is a popular topic, but many Fear & Greed indexes function as black boxes: they lack transparency, exaggerate sentiment, and rely ...",
    "image": "https://images.unsplash.com/photo-1636690498207-d7b393423b9a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMTc3M3wwfDF8c2VhcmNofDM2OHx8ZGF0YXxlbnwwfHx8fDE3NDI0MTI5MDl8MA&ixlib=rb-4.0.3&q=80&w=2000",
    "publishedAt": "2025-03-19T20:37:55.000+01:00",
    "updatedAt": "2025-03-19T20:37:55.000+01:00",
    "author": "Fernando Nikolic",
    "tags": [
      "Opinion",
      "#Import 2025-12-30 07:22"
    ]
  },
  "perception-weekly-70": {
    "title": "Perception Weekly #70",
    "description": "💡Last week’s discussions highlighted the complex interplay of regulatory challenges, institutional investment trends, and state-level Bitcoin legislation. ...",
    "image": "https://cms.perception.to/content/images/2025/03/Perception-Weekly-Cover--2-.png",
    "publishedAt": "2025-03-04T15:51:09.000+01:00",
    "updatedAt": "2025-03-04T15:51:09.000+01:00",
    "author": "Fernando Nikolic",
    "tags": [
      "Weekly Digest",
      "#Import 2025-12-30 07:22"
    ]
  },
  "the-quiet-shift-in-how-information-spreads": {
    "title": "The Quiet Shift in How Information Spreads",
    "description": "Since 2021, I’ve led the Marketing & Communications department at Blockstream, and one thing has become increasingly clear: the way information spreads onlin...",
    "image": "https://images.unsplash.com/photo-1531297484001-80022131f5a1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMTc3M3wwfDF8c2VhcmNofDIyfHxpbmZvcm1hdGlvbnxlbnwwfHx8fDE3NDA2NjAxMzN8MA&ixlib=rb-4.0.3&q=80&w=2000",
    "publishedAt": "2025-02-27T19:54:13.000+01:00",
    "updatedAt": "2025-02-27T19:54:12.000+01:00",
    "author": "Fernando Nikolic",
    "tags": [
      "Opinion",
      "#Import 2025-12-30 07:22"
    ]
  },
  "perception-weekly-69": {
    "title": "Perception Weekly #69",
    "description": "💡We’ve just rolled out a powerful new feature on Perception! Now, you can select any media outlet and instantly analyze how they’ve covered Bitcoin—from th...",
    "image": "https://cms.perception.to/content/images/2025/02/Perception-Weekly-Cover--1-.png",
    "publishedAt": "2025-02-24T16:11:54.000+01:00",
    "updatedAt": "2025-02-24T16:11:54.000+01:00",
    "author": "Fernando Nikolic",
    "tags": [
      "Weekly Digest",
      "#Import 2025-12-30 07:22"
    ]
  },
  "perception-weekly-68": {
    "title": "Perception Weekly #68",
    "description": "💡The Perception platform is now live in alpha for you to test. The platform is designed for researchers, journalists, and traders, offering something truly...",
    "image": "https://cms.perception.to/content/images/2025/02/Perception-Weekly-Cover.png",
    "publishedAt": "2025-02-17T15:38:38.000+01:00",
    "updatedAt": "2025-02-17T15:38:37.000+01:00",
    "author": "Fernando Nikolic",
    "tags": [
      "Weekly Digest",
      "#Import 2025-12-30 07:22"
    ]
  },
  "opinion-msms-potential-narrative-casting-bitcoiners-as-the-1": {
    "title": "OPINION: MSM’s Potential Narrative Casting Bitcoiners as the 1%",
    "description": "Some of last week's headlines have drawn an interesting parallel between the world’s wealthiest individuals and Bitcoin holders. While Donald Trump’s inaugu...",
    "image": "https://images.unsplash.com/photo-1560789191-20b054060a9b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMTc3M3wwfDF8c2VhcmNofDd8fHdlZiUyMHxlbnwwfHx8fDE3Mzc5NzMwMDR8MA&ixlib=rb-4.0.3&q=80&w=2000",
    "publishedAt": "2025-01-27T16:23:39.000+01:00",
    "updatedAt": "2025-01-27T16:23:38.000+01:00",
    "author": "Fernando Nikolic",
    "tags": [
      "Opinion",
      "#Import 2025-12-30 07:22"
    ]
  },
  "the-article-that-aged-like-milk-nyts-bitcoin-collapse-prediction": {
    "title": "The Article That Aged Like Milk: NYT’s Bitcoin ‘Collapse’ Prediction",
    "description": "How a Finance Professor Got Bitcoin Wrong (And Missed the Greatest Rally Yet)",
    "image": "https://cms.perception.to/content/images/2025/01/Screenshot-2025-01-16-at-12.42.46-PM.png",
    "publishedAt": "2025-01-16T16:08:10.000+01:00",
    "updatedAt": "2025-01-16T16:08:09.000+01:00",
    "author": "Fernando Nikolic",
    "tags": [
      "Opinion",
      "#Import 2025-12-30 07:22"
    ]
  },
  "perception-weekly-67": {
    "title": "Perception Weekly #67",
    "description": "💡The Perception platform is now live in alpha for you to test. The platform is designed for researchers, journalists, and traders, offering something truly...",
    "image": "https://cms.perception.to/content/images/2025/01/Perception-Weekly-Cover.png",
    "publishedAt": "2025-01-13T15:00:02.000+01:00",
    "updatedAt": "2025-01-13T15:00:02.000+01:00",
    "author": "BTCP Staff",
    "tags": [
      "Weekly Digest",
      "#Import 2025-12-30 07:22"
    ]
  },
  "weekly-recap-66": {
    "title": "Weekly Recap #66",
    "description": "👋A MESSAGE FROM THE FOUNDER: Hey, Fernando here – Happy New Year! 🎉 Sorry for the radio silence here, but I’ve been busy over the holidays putting the fi...",
    "image": "https://cms.perception.to/content/images/2025/01/Perception-Weekly.png",
    "publishedAt": "2025-01-06T15:00:54.000+01:00",
    "updatedAt": "2025-01-06T15:00:55.000+01:00",
    "author": "Fernando Nikolic",
    "tags": [
      "Weekly Digest",
      "#Import 2025-12-30 07:22"
    ]
  },
  "opinion-the-era-of-centralized-narratives-is-over": {
    "title": "Opinion: The era of centralized narratives is over.",
    "description": "The very journalists and companies that once dictated public narratives are fleeing platforms that no longer cater to their centralized vision of control.",
    "image": "https://images.unsplash.com/photo-1692756227212-554860533282?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMTc3M3wwfDF8c2VhcmNofDc0fHxqb3VybmFsaXN0fGVufDB8fHx8MTczMjU2NzQ1N3ww&ixlib=rb-4.0.3&q=80&w=2000",
    "publishedAt": "2024-11-25T21:58:51.000+01:00",
    "updatedAt": "2025-01-09T08:49:52.000+01:00",
    "author": "Fernando Nikolic",
    "tags": [
      "Opinion",
      "#Import 2025-12-30 07:22"
    ]
  },
  "weekly-recap-64": {
    "title": "Weekly Recap #64",
    "description": "💡Here’s a snapshot of last week’s Bitcoin market insights, curated by Bitcoin Perception. Bitcoin Perception will soon offer real-time data on hot discussi...",
    "image": "https://cms.perception.to/content/images/2024/11/Blue-and-White-Gradient-Tech-Instagram-Post--5-.png",
    "publishedAt": "2024-11-04T15:00:33.000+01:00",
    "updatedAt": "2024-11-04T15:00:33.000+01:00",
    "author": "BTCP Staff",
    "tags": [
      "Weekly Digest",
      "#Import 2025-12-30 07:22"
    ]
  },
  "weekly-recap-63": {
    "title": "Weekly Recap #63",
    "description": "💡The past week’s coverage reflects a multifaceted view of Bitcoin’s global position: • Positive Trends: Institutional adoption is rising, with increased ET...",
    "image": "https://cms.perception.to/content/images/2024/10/Blue-and-White-Gradient-Tech-Instagram-Post--4-.png",
    "publishedAt": "2024-10-28T15:00:10.000+01:00",
    "updatedAt": "2024-10-28T15:00:14.000+01:00",
    "author": "BTCP Staff",
    "tags": [
      "Weekly Digest",
      "#Import 2025-12-30 07:22"
    ]
  },
  "weekly-recap-62": {
    "title": "Weekly Recap #62",
    "description": "💡At Bitcoin Perception, we’re working on building a powerful platform that will give you real-time, on-demand access to the data used in this report. This ...",
    "image": "https://cms.perception.to/content/images/2024/09/Blue-and-White-Gradient-Tech-Instagram-Post--3-.png",
    "publishedAt": "2024-09-30T15:00:55.000+02:00",
    "updatedAt": "2024-09-30T15:00:57.000+02:00",
    "author": "BTCP Staff",
    "tags": [
      "Weekly Digest",
      "#Import 2025-12-30 07:22"
    ]
  },
  "weekly-recap-61": {
    "title": "Weekly Recap #61",
    "description": "💡At Bitcoin Perception, we’re working on building a powerful platform that will give you real-time, on-demand access to the data used in this report. This ...",
    "image": "https://cms.perception.to/content/images/2024/09/Blue-and-White-Gradient-Tech-Instagram-Post--2-.png",
    "publishedAt": "2024-09-23T15:00:54.000+02:00",
    "updatedAt": "2025-01-09T08:48:30.000+01:00",
    "author": "BTCP Staff",
    "tags": [
      "Weekly Digest",
      "#Import 2025-12-30 07:22"
    ]
  },
  "weekly-recap-60": {
    "title": "Weekly Recap #60",
    "description": "💡At Bitcoin Perception, we’re working on building a powerful platform that will give you real-time, on-demand access to the data used in this report. This ...",
    "image": "https://cms.perception.to/content/images/2024/09/Blue-and-White-Gradient-Tech-Instagram-Post--1-.png",
    "publishedAt": "2024-09-16T15:00:17.000+02:00",
    "updatedAt": "2025-01-09T08:48:41.000+01:00",
    "author": "BTCP Staff",
    "tags": [
      "Weekly Digest",
      "#Import 2025-12-30 07:22"
    ]
  },
  "weekly-recap-59": {
    "title": "Weekly Recap #59",
    "description": "Date range: September 2 - September 8, 2024 Weekly Snapshot 📸 News 🗞️ 1. Metaplanet's partnership with SBI Holdings' crypto division to enhance...",
    "image": "https://cms.perception.to/content/images/2024/09/Blue-and-White-Gradient-Tech-Instagram-Post-1.png",
    "publishedAt": "2024-09-09T15:00:34.000+02:00",
    "updatedAt": "2025-01-09T08:48:49.000+01:00",
    "author": "BTCP Staff",
    "tags": [
      "Weekly Digest",
      "#Import 2025-12-30 07:22"
    ]
  },
  "weekly-recap-58": {
    "title": "Weekly Recap #58",
    "description": "Date range: August 26 - September 1, 2024 Weekly Snapshot 📸 News 🗞️ NOSTR as a Telegram Substitute Sentiment: Neutral Mainstream media has ...",
    "image": "https://cms.perception.to/content/images/2024/09/Blue-and-White-Gradient-Tech-Instagram-Post.png",
    "publishedAt": "2024-09-02T16:19:30.000+02:00",
    "updatedAt": "2025-01-09T08:48:55.000+01:00",
    "author": "BTCP Staff",
    "tags": [
      "Weekly Digest",
      "#Import 2025-12-30 07:22"
    ]
  },
  "weekly-recap-57": {
    "title": "Weekly Recap #57",
    "description": "Date range: August 19 - August 25, 2024 Weekly Snapshot 📸 Hot Discussions 🔥 * Discussions around Bitcoin's price hovering around $60,000, alon...",
    "image": "https://cms.perception.to/content/images/2024/08/Blue-and-White-Gradient-Tech-Instagram-Post.png",
    "publishedAt": "2024-08-26T15:00:30.000+02:00",
    "updatedAt": "2024-08-26T15:00:29.000+02:00",
    "author": "BTCP Staff",
    "tags": [
      "Weekly Digest",
      "#Import 2025-12-30 07:22"
    ]
  },
  "weekly-recap-56": {
    "title": "Weekly Recap #56",
    "description": "Date range: August 12 - August 18, 2024 Weekly Snapshot 📸 Hot Discussions 🔥 1. 18% of Democrats Have Bought Bitcoin, More to Follow: New Poll ...",
    "image": "https://cms.perception.to/content/images/2024/08/Blue-White-Gradient-Instagram.png",
    "publishedAt": "2024-08-19T15:00:06.000+02:00",
    "updatedAt": "2025-01-09T08:49:01.000+01:00",
    "author": "BTCP Staff",
    "tags": [
      "Weekly Digest",
      "#Import 2025-12-30 07:22"
    ]
  },
  "weekly-recap-55": {
    "title": "Weekly Recap #55",
    "description": "EOW closing BTC price: $58,829 Date range: August 5 - August 11, 2024 Weekly Snapshot 📸 Hot Discussions 🔥 1. State pension funds are explori...",
    "image": "https://cms.perception.to/content/images/2024/08/Blue-White-Gradient-Instagram--4-.png",
    "publishedAt": "2024-08-12T15:00:10.000+02:00",
    "updatedAt": "2024-08-19T23:02:29.000+02:00",
    "author": "BTCP Staff",
    "tags": [
      "Weekly Digest",
      "#Import 2025-12-30 07:22"
    ]
  },
  "weekly-recap-54": {
    "title": "Weekly Recap #54",
    "description": "EOW closing BTC price: $58,138 Date range: July 29 - August 4, 2024 Weekly Snapshot 📸 💡Welcome to this week’s comprehensive report on the most sign...",
    "image": "https://cms.perception.to/content/images/2024/08/Blue-White-Gradient-Instagram--3-.png",
    "publishedAt": "2024-08-05T15:00:42.000+02:00",
    "updatedAt": "2024-08-12T17:14:52.000+02:00",
    "author": "BTCP Staff",
    "tags": [
      "Weekly Digest",
      "#Import 2025-12-30 07:22"
    ]
  },
  "media-frenzy-over-trump-weekly-recap-53": {
    "title": "Weekly Recap #53",
    "description": "❗Saturday's Trump appearance at the Bitcoin conference in Nashville sparked an all-time high in Trump/Bitcoin coverage. This week's report dives into the ...",
    "image": "https://cms.perception.to/content/images/2024/07/Blue-White-Gradient-Instagram--2--1.png",
    "publishedAt": "2024-07-29T15:00:39.000+02:00",
    "updatedAt": "2024-08-12T17:17:52.000+02:00",
    "author": "BTCP Staff",
    "tags": [
      "Weekly Digest",
      "#Import 2025-12-30 07:22"
    ]
  },
  "weekly-media-recap-52": {
    "title": "Weekly Media Recap #52",
    "description": "Bitcoin Perception celebrates 1 year! 🎉",
    "image": "https://cms.perception.to/content/images/2024/07/Blue-White-Gradient-Instagram--3-.png",
    "publishedAt": "2024-07-22T15:00:58.000+02:00",
    "updatedAt": "2024-07-22T15:00:58.000+02:00",
    "author": "BTCP Staff",
    "tags": [
      "Weekly Digest",
      "#Import 2025-12-30 07:22"
    ]
  },
  "mainstream-media-bias-will-only-get-worse": {
    "title": "Mainstream Media Bias Will Only Get Worse",
    "description": "This is an op-ed originally published in Bitcoin Magazine.",
    "image": "https://cms.perception.to/content/images/2024/07/Future-Tech-YouTube-Banner.png",
    "publishedAt": "2024-07-18T15:00:48.000+02:00",
    "updatedAt": "2024-07-18T15:00:47.000+02:00",
    "author": "Fernando Nikolic",
    "tags": [
      "Opinion",
      "#Import 2025-12-30 07:22"
    ]
  },
  "weekly-media-recap-51": {
    "title": "Weekly Media Recap #51",
    "description": "Bitcoin, as covered in the mainstream media.",
    "image": "https://cms.perception.to/content/images/2024/07/Blue-White-Gradient-Instagram--2-.png",
    "publishedAt": "2024-07-15T15:00:31.000+02:00",
    "updatedAt": "2024-08-07T21:41:48.000+02:00",
    "author": "Fernando Nikolic",
    "tags": [
      "Weekly Digest",
      "#Import 2025-12-30 07:22"
    ]
  },
  "weekly-media-recap-50": {
    "title": "Weekly Media Recap #50",
    "description": "Bitcoin, as covered in the mainstream media.",
    "image": "https://cms.perception.to/content/images/2024/07/Blue-White-Gradient-Instagram--1-.png",
    "publishedAt": "2024-07-08T15:00:04.000+02:00",
    "updatedAt": "2024-07-08T15:00:04.000+02:00",
    "author": "BTCP Staff",
    "tags": [
      "Weekly Digest",
      "#Import 2025-12-30 07:22"
    ]
  },
  "weekly-media-recap-49": {
    "title": "Weekly Media Recap #49",
    "description": "Bitcoin, as covered in the mainstream media.",
    "image": "https://cms.perception.to/content/images/2024/06/Blue-White-Gradient-Instagram-2.png",
    "publishedAt": "2024-07-01T15:00:03.000+02:00",
    "updatedAt": "2024-07-01T15:00:02.000+02:00",
    "author": "Fernando Nikolic",
    "tags": [
      "Weekly Digest",
      "#Import 2025-12-30 07:22"
    ]
  },
  "left-leaning-outlets-anti-bitcoin-bias-is-getting-amplified-by-trumps-endorsement": {
    "title": "Left-Leaning Outlets Amplify Their Anti-Bitcoin Bias Following Trum...",
    "description": "Is it about Bitcoin? Or is it yet another front in the ongoing political battles duked out in the media landscape?",
    "image": "https://images.unsplash.com/photo-1580128660010-fd027e1e587a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMTc3M3wwfDF8c2VhcmNofDF8fHRydW1wfGVufDB8fHx8MTcxODc0NjM4N3ww&ixlib=rb-4.0.3&q=80&w=2000",
    "publishedAt": "2024-06-26T16:00:57.000+02:00",
    "updatedAt": "2025-01-09T08:49:38.000+01:00",
    "author": "Fernando Nikolic",
    "tags": [
      "Opinion",
      "#Import 2025-12-30 07:22"
    ]
  },
  "weekly-media-recap-47": {
    "title": "Weekly Media Recap #47",
    "description": "Bitcoin, as covered in the mainstream media.",
    "image": "https://cms.perception.to/content/images/2024/06/Blue-White-Gradient-Instagram--1-.png",
    "publishedAt": "2024-06-17T15:00:03.000+02:00",
    "updatedAt": "2024-06-17T17:45:20.000+02:00",
    "author": "BTCP Staff",
    "tags": [
      "Weekly Digest",
      "#Import 2025-12-30 07:22"
    ]
  },
  "weekly-media-recap-46": {
    "title": "Weekly Media Recap #46",
    "description": "EOW closing BTC price: $69,638 Date range: June 3 - June 9, 2024 In this report: How the mainstream media covered these major stories: 1. Mining Industry...",
    "image": "https://cms.perception.to/content/images/2024/06/Blue-White-Gradient-Instagram.png",
    "publishedAt": "2024-06-10T15:00:05.000+02:00",
    "updatedAt": "2024-06-10T15:00:04.000+02:00",
    "author": "BTCP Staff",
    "tags": [
      "Weekly Digest",
      "#Import 2025-12-30 07:22"
    ]
  },
  "weekly-media-recap-45": {
    "title": "Weekly Media Recap #45",
    "description": "Bitcoin, as covered in the mainstream media.",
    "image": "https://cms.perception.to/content/images/2024/06/Blue-White-Gradient.png",
    "publishedAt": "2024-06-03T15:00:23.000+02:00",
    "updatedAt": "2024-06-05T13:05:05.000+02:00",
    "author": "BTCP Staff",
    "tags": [
      "Weekly Digest",
      "#Import 2025-12-30 07:22"
    ]
  },
  "weekly-media-recap-44": {
    "title": "Weekly Media Recap #44",
    "description": "Bitcoin, as covered in the mainstream media.",
    "image": "https://cms.perception.to/content/images/2024/05/Blue-White--1-.png",
    "publishedAt": "2024-05-27T15:00:23.000+02:00",
    "updatedAt": "2024-05-27T15:00:22.000+02:00",
    "author": "BTCP Staff",
    "tags": [
      "Weekly Digest",
      "#Import 2025-12-30 07:22"
    ]
  },
  "weekly-media-recap-43": {
    "title": "Weekly Media Recap #43",
    "description": "Bitcoin, as covered in the mainstream media.",
    "image": "https://cms.perception.to/content/images/2024/05/Blue-White.png",
    "publishedAt": "2024-05-20T15:00:26.000+02:00",
    "updatedAt": "2024-05-20T15:00:25.000+02:00",
    "author": "BTCP Staff",
    "tags": [
      "Weekly Digest",
      "#Import 2025-12-30 07:22"
    ]
  },
  "weekly-media-recap-42": {
    "title": "Weekly Media Recap #42",
    "description": "Bitcoin, as covered in the mainstream media.",
    "image": "https://cms.perception.to/content/images/2024/05/Blue-White--3-.png",
    "publishedAt": "2024-05-13T15:00:01.000+02:00",
    "updatedAt": "2024-05-13T15:23:37.000+02:00",
    "author": "BTCP Staff",
    "tags": [
      "Weekly Digest",
      "#Import 2025-12-30 07:22"
    ]
  },
  "weekly-media-recap-41": {
    "title": "Weekly Media Recap #41",
    "description": "Bitcoin, as covered in the mainstream media.",
    "image": "https://cms.perception.to/content/images/2024/05/Blue-White--2-.png",
    "publishedAt": "2024-05-06T15:00:10.000+02:00",
    "updatedAt": "2024-05-06T15:00:10.000+02:00",
    "author": "BTCP Staff",
    "tags": [
      "Weekly Digest",
      "#Import 2025-12-30 07:22"
    ]
  },
  "weekly-media-recap-40": {
    "title": "Weekly Media Recap #40",
    "description": "Bitcoin, as covered in the mainstream media.",
    "image": "https://cms.perception.to/content/images/2024/04/Blue-White-1.png",
    "publishedAt": "2024-04-29T15:00:57.000+02:00",
    "updatedAt": "2024-04-29T15:00:56.000+02:00",
    "author": "BTCP Staff",
    "tags": [
      "Weekly Digest",
      "#Import 2025-12-30 07:22"
    ]
  },
  "weekly-media-recap-39": {
    "title": "Weekly Media Recap #39",
    "description": "Bitcoin, as covered in the mainstream media.",
    "image": "https://cms.perception.to/content/images/2024/04/Blue-White-Gradient-Instagram-1.png",
    "publishedAt": "2024-04-22T15:00:07.000+02:00",
    "updatedAt": "2024-04-22T15:00:06.000+02:00",
    "author": "BTCP Staff",
    "tags": [
      "Weekly Digest",
      "#Import 2025-12-30 07:22"
    ]
  },
  "weekly-media-recap-38": {
    "title": "Weekly Media Recap #38",
    "description": "Bitcoin, as covered in the mainstream media.",
    "image": "https://cms.perception.to/content/images/2024/04/Blue-White--1-.png",
    "publishedAt": "2024-04-15T15:00:43.000+02:00",
    "updatedAt": "2024-04-15T15:00:42.000+02:00",
    "author": "BTCP Staff",
    "tags": [
      "Weekly Digest",
      "#Import 2025-12-30 07:22"
    ]
  },
  "weekly-media-recap-37": {
    "title": "Weekly Media Recap #37",
    "description": "Bitcoin, as covered in the mainstream media.",
    "image": "https://cms.perception.to/content/images/2024/04/Blue-White-Gradient-Instagram.png",
    "publishedAt": "2024-04-08T15:00:05.000+02:00",
    "updatedAt": "2024-04-08T15:00:04.000+02:00",
    "author": "BTCP Staff",
    "tags": [
      "Weekly Digest",
      "#Import 2025-12-30 07:22"
    ]
  },
  "weekly-media-recap-36": {
    "title": "Weekly Media Recap #36",
    "description": "Bitcoin, as covered in the mainstream media.",
    "image": "https://cms.perception.to/content/images/2024/03/Blue-White-1.png",
    "publishedAt": "2024-04-01T15:00:47.000+02:00",
    "updatedAt": "2024-04-01T15:00:47.000+02:00",
    "author": "BTCP Staff",
    "tags": [
      "Weekly Digest",
      "#Import 2025-12-30 07:22"
    ]
  },
  "weekly-recap-35": {
    "title": "Weekly Media Recap #35",
    "description": "Bitcoin, as covered in the mainstream media.",
    "image": "https://cms.perception.to/content/images/2024/03/Blue-White-Gradient-1.png",
    "publishedAt": "2024-03-25T15:00:48.000+01:00",
    "updatedAt": "2024-03-25T15:00:47.000+01:00",
    "author": "BTCP Staff",
    "tags": [
      "Weekly Digest",
      "#Import 2025-12-30 07:22"
    ]
  },
  "weekly-media-recap-34": {
    "title": "Weekly Media Recap #34",
    "description": "Bitcoin, as covered in the mainstream media.",
    "image": "https://cms.perception.to/content/images/2024/03/Blue-White--1-.png",
    "publishedAt": "2024-03-18T15:01:09.000+01:00",
    "updatedAt": "2024-03-18T17:28:38.000+01:00",
    "author": "BTCP Staff",
    "tags": [
      "Weekly Digest",
      "#Import 2025-12-30 07:22"
    ]
  },
  "the-presss-altcoin-obsession-a-curious-case-of-misplaced-focus": {
    "title": "Asleep At The Wheel: The MSM's Fixation With Altcoins",
    "description": "How the media's altcoin obsession misses the mark during new all-time highs.",
    "image": "https://cms.perception.to/content/images/2024/03/Asleep.jpg",
    "publishedAt": "2024-03-13T19:16:31.000+01:00",
    "updatedAt": "2024-03-13T19:24:55.000+01:00",
    "author": "Fernando Nikolic",
    "tags": [
      "Opinion",
      "#Import 2025-12-30 07:22"
    ]
  },
  "weekly-media-recap-33": {
    "title": "Weekly Media Recap #33",
    "description": "Bitcoin, as covered in the mainstream media.",
    "image": "https://cms.perception.to/content/images/2024/03/Blue-White-Gradient.png",
    "publishedAt": "2024-03-11T15:00:26.000+01:00",
    "updatedAt": "2024-03-11T15:00:25.000+01:00",
    "author": "BTCP Staff",
    "tags": [
      "Weekly Digest",
      "#Import 2025-12-30 07:22"
    ]
  },
  "weekly-media-recap-32": {
    "title": "Weekly Media Recap #32",
    "description": "Bitcoin, as covered in the mainstream media.",
    "image": "https://cms.perception.to/content/images/2024/03/Blue-White.png",
    "publishedAt": "2024-03-04T15:00:02.000+01:00",
    "updatedAt": "2024-03-04T15:00:02.000+01:00",
    "author": "BTCP Staff",
    "tags": [
      "Weekly Digest",
      "#Import 2025-12-30 07:22"
    ]
  },
  "weekly-media-recap-31": {
    "title": "Weekly Media Recap #31",
    "description": "Bitcoin, as covered in the mainstream media.",
    "image": "https://cms.perception.to/content/images/2024/02/Blue-White--3--5.png",
    "publishedAt": "2024-02-26T15:00:12.000+01:00",
    "updatedAt": "2024-03-19T14:16:35.000+01:00",
    "author": "BTCP Staff",
    "tags": [
      "Weekly Digest",
      "#Import 2025-12-30 07:22"
    ]
  },
  "comunicado-de-prensa-nuevo-informe-revela-el-sentimiento-de-los-medios-sobre-la-adopcion-de-bitcoin-en-el-salvador": {
    "title": "Comunicado de Prensa: Nuevo Informe Revela el Sentimiento de los Me...",
    "description": "La firma de investigación de medios Bitcoin Perception anunció hoy el lanzamiento de su primer informe de investigación extenso, titulado \"Bitcoin como Moned...",
    "image": "https://cms.perception.to/content/images/2024/02/Pika--3--1.png",
    "publishedAt": "2024-02-20T13:00:34.000+01:00",
    "updatedAt": "2024-02-20T13:00:33.000+01:00",
    "author": "BTCP Staff",
    "tags": [
      "Press Releases",
      "#Import 2025-12-30 07:22"
    ]
  },
  "press-release-new-report-reveals-media-sentiment-on-el-salvadors-bitcoin-adoption": {
    "title": "Press Release: New Report Reveals Media Sentiment on El Salvador's ...",
    "description": "Media research firm Bitcoin Perception today announced the release of its first long-form research report, titled \"Bitcoin as Legal Tender: El Salvador's Pio...",
    "image": "https://cms.perception.to/content/images/2024/02/Pika--2--1.png",
    "publishedAt": "2024-02-20T13:00:32.000+01:00",
    "updatedAt": "2024-02-20T13:00:32.000+01:00",
    "author": "BTCP Staff",
    "tags": [
      "Press Releases",
      "#Import 2025-12-30 07:22"
    ]
  },
  "bitcoin-as-legal-tender-el-salvadors-groundbreaking-decision-and-the-salvadorian-mainstream-medias-reaction": {
    "title": "Bitcoin as Legal Tender: El Salvador's Groundbreaking Decision and ...",
    "description": "A Bitcoin Perception report written by Luis David Esparragoza and Fernando Nikolić.",
    "image": "https://cms.perception.to/content/images/2024/02/Pika--2-.png",
    "publishedAt": "2024-02-20T13:00:29.000+01:00",
    "updatedAt": "2024-03-29T16:51:26.000+01:00",
    "author": "BTCP Staff",
    "tags": [
      "Reports",
      "#Import 2025-12-30 07:22"
    ]
  },
  "bitcoin-como-moneda-de-curso-legal-la-decision-innovadora-de-el-salvador-y-la-reaccion-de-los-medios-de-comunicacion-salvadorenos": {
    "title": "Bitcoin como Moneda de Curso Legal: La Decisión Innovadora de El Sa...",
    "description": "Un reporte de Bitcoin Perception por Luis David Esparragoza y Fernando Nikolić",
    "image": "https://cms.perception.to/content/images/2024/02/Pika--3-.png",
    "publishedAt": "2024-02-20T13:00:26.000+01:00",
    "updatedAt": "2024-04-27T22:27:32.000+02:00",
    "author": "BTCP Staff",
    "tags": [
      "Reports",
      "#Import 2025-12-30 07:22"
    ]
  },
  "weekly-media-recap-30": {
    "title": "Weekly Media Recap #30",
    "description": "Bitcoin, as covered in the mainstream media.",
    "image": "https://cms.perception.to/content/images/2024/02/Blue-White-Gradient-Instagram--2--4.png",
    "publishedAt": "2024-02-19T15:00:49.000+01:00",
    "updatedAt": "2024-02-19T15:00:48.000+01:00",
    "author": "BTCP Staff",
    "tags": [
      "Weekly Digest",
      "#Import 2025-12-30 07:22"
    ]
  },
  "a-satoshi-nakamoto-cosplay-gone-too-far": {
    "title": "A Satoshi Nakamoto Cosplay Gone Too Far",
    "description": "It's time to stop lending the spotlight to a 'tech whiz' in a pinstripe suit, claiming to be something he's not.",
    "image": "https://cms.perception.to/content/images/2024/02/Craig-Wright-COP.png",
    "publishedAt": "2024-02-14T16:26:42.000+01:00",
    "updatedAt": "2024-04-27T22:26:40.000+02:00",
    "author": "Fernando Nikolic",
    "tags": [
      "Opinion",
      "#Import 2025-12-30 07:22"
    ]
  },
  "weekly-media-recap-29": {
    "title": "Weekly Media Recap #29",
    "description": "Bitcoin, as covered in the mainstream media.",
    "image": "https://cms.perception.to/content/images/2024/02/Blue-White--1--7.png",
    "publishedAt": "2024-02-12T15:00:44.000+01:00",
    "updatedAt": "2024-02-12T15:00:54.000+01:00",
    "author": "Fernando Nikolic",
    "tags": [
      "Weekly Digest",
      "#Import 2025-12-30 07:22"
    ]
  },
  "a-closer-examination-of-bitcoin-coverage-in-el-salvador": {
    "title": "A Closer Examination of Bitcoin Coverage During El Salvador's Presi...",
    "description": "The recent media focus on El Salvador serves as a stark illustration of media bias and its consequences.",
    "image": "https://cms.perception.to/content/images/2024/02/El-Salvador-Election-Nayib-Bukele.jpg",
    "publishedAt": "2024-02-10T17:07:29.000+01:00",
    "updatedAt": "2024-02-10T17:07:29.000+01:00",
    "author": "Fernando Nikolic",
    "tags": [
      "Opinion",
      "#Import 2025-12-30 07:22"
    ]
  },
  "weekly-media-recap-28": {
    "title": "Weekly Media Recap #28",
    "description": "Bitcoin, as covered in the MSM last week.",
    "image": "https://cms.perception.to/content/images/2024/02/Blue-White-Gradient-Instagram-2.png",
    "publishedAt": "2024-02-07T14:19:38.000+01:00",
    "updatedAt": "2024-02-11T10:41:54.000+01:00",
    "author": "Fernando Nikolic",
    "tags": [
      "Weekly Digest",
      "#Import 2025-12-30 07:22"
    ]
  },
  "mainstream-pundits-are-the-new-bitcoin": {
    "title": "Mainstream pundits are the new Bitcoin maxis",
    "description": "The Cypherpunk transformation reporters didn't see coming.",
    "image": "https://images.unsplash.com/photo-1580171401298-4c2c0c44cc43?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMTc3M3wwfDF8c2VhcmNofDF8fHJlcG9ydGVyfGVufDB8fHx8MTcwNzA2Njg1MXww&ixlib=rb-4.0.3&q=80&w=2000",
    "publishedAt": "2024-01-31T16:22:58.000+01:00",
    "updatedAt": "2024-04-27T22:26:51.000+02:00",
    "author": "Fernando Nikolic",
    "tags": [
      "Opinion",
      "#Import 2025-12-30 07:22"
    ]
  },
  "weekly-media-recap-27": {
    "title": "Weekly Media Recap #27",
    "description": "Bitcoin, as covered in the MSM last week.",
    "image": "https://cms.perception.to/content/images/2024/02/Blue-White.png",
    "publishedAt": "2024-01-29T15:01:12.000+01:00",
    "updatedAt": "2024-02-11T10:41:36.000+01:00",
    "author": "Fernando Nikolic",
    "tags": [
      "Weekly Digest",
      "#Import 2025-12-30 07:22"
    ]
  },
  "the-last-stand": {
    "title": "The Last Stand",
    "description": "The financial press' typewriters are trembling!",
    "image": "https://cms.perception.to/content/images/2024/02/Last-Stand.webp",
    "publishedAt": "2024-01-24T15:01:05.000+01:00",
    "updatedAt": "2024-02-11T10:31:29.000+01:00",
    "author": "Fernando Nikolic",
    "tags": [
      "Opinion",
      "#Import 2025-12-30 07:22"
    ]
  },
  "weekly-media-recap-26": {
    "title": "Weekly Media Recap #26",
    "description": "Bitcoin, as covered in the MSM last week.",
    "image": "https://cms.perception.to/content/images/2024/02/Blue-White--1-.png",
    "publishedAt": "2024-01-22T15:01:08.000+01:00",
    "updatedAt": "2024-02-11T10:41:18.000+01:00",
    "author": "Fernando Nikolic",
    "tags": [
      "Weekly Digest",
      "#Import 2025-12-30 07:22"
    ]
  },
  "bitcoin-etf-the-movie": {
    "title": "Bitcoin ETF: The Movie",
    "description": "Welcome, Boomers, to the greatest show on Earth.",
    "image": "https://cms.perception.to/content/images/2024/02/-1x-1.jpg",
    "publishedAt": "2024-01-17T13:57:04.000+01:00",
    "updatedAt": "2024-03-24T12:23:14.000+01:00",
    "author": "Fernando Nikolic",
    "tags": [
      "Opinion",
      "#Import 2025-12-30 07:22"
    ]
  },
  "end-the-fed-still-in-play": {
    "title": "Weekly Media Recap #25",
    "description": "End The Fed Still In Play",
    "image": "https://cms.perception.to/content/images/2024/02/Blue-White--3-.png",
    "publishedAt": "2024-01-15T15:01:31.000+01:00",
    "updatedAt": "2024-02-11T10:40:59.000+01:00",
    "author": "Fernando Nikolic",
    "tags": [
      "Weekly Digest",
      "#Import 2025-12-30 07:22"
    ]
  },
  "my-new-year-resolution-is-bitcoin": {
    "title": "My New Year Resolution Is Bitcoin, Too",
    "description": "This Week's Spotlight: The Financial Times",
    "image": "https://cms.perception.to/content/images/2024/02/New-Year-Bitcoin.webp",
    "publishedAt": "2024-01-09T23:01:41.000+01:00",
    "updatedAt": "2024-02-04T17:54:06.000+01:00",
    "author": "Fernando Nikolic",
    "tags": [
      "Opinion",
      "#Import 2025-12-30 07:22"
    ]
  },
  "im-here-to-fix-the-block-size-problem": {
    "title": "Weekly Media Recap #24",
    "description": "I'm Here To Fix The Block Size Problem",
    "image": "https://cms.perception.to/content/images/2024/02/Blue-White-Gradient-Instagram.png",
    "publishedAt": "2024-01-08T15:31:13.000+01:00",
    "updatedAt": "2024-02-11T10:40:24.000+01:00",
    "author": "Fernando Nikolic",
    "tags": [
      "Weekly Digest",
      "#Import 2025-12-30 07:22"
    ]
  },
  "not-your-typical-full-year-roundup": {
    "title": "Not Your Typical Full-Year Roundup",
    "description": "The year in review and what you can expect in 2024.",
    "image": "https://perception-og-image.fernandonikolic.workers.dev/api/og-image?title=Not+Your+Typical+Full-Year+Roundup&description=The+year+in+review+and+what+you+can+expect+in+2024.+&theme=dark",
    "publishedAt": "2024-01-01T15:00:17.000+01:00",
    "updatedAt": "2024-02-07T14:32:53.000+01:00",
    "author": "Fernando Nikolic",
    "tags": [
      "Opinion",
      "#Import 2025-12-30 07:22"
    ]
  },
  "you-are-not-bullish-enough": {
    "title": "Weekly Media Recap #23",
    "description": "You Are Not Bullish Enough",
    "image": "https://cms.perception.to/content/images/2024/02/Blue-White-Gradient-Instagram--2-.png",
    "publishedAt": "2023-12-18T15:01:42.000+01:00",
    "updatedAt": "2024-02-11T10:32:31.000+01:00",
    "author": "Fernando Nikolic",
    "tags": [
      "Weekly Digest",
      "#Import 2025-12-30 07:22"
    ]
  },
  "jamie-dimon-vs-nayib-bukele": {
    "title": "Weekly Media Recap #22",
    "description": "Jamie Dimon vs. Nayib Bukele",
    "image": "https://cms.perception.to/content/images/2024/02/Blue-White-Gradient-Instagram-1.png",
    "publishedAt": "2023-12-11T15:01:35.000+01:00",
    "updatedAt": "2024-02-11T10:39:16.000+01:00",
    "author": "Fernando Nikolic",
    "tags": [
      "Weekly Digest",
      "#Import 2025-12-30 07:22"
    ]
  },
  "a-swimming-pool-full-of-luddite-tears": {
    "title": "Weekly Media Recap #21",
    "description": "This week's spotlight: The Independent & BBC",
    "image": "https://cms.perception.to/content/images/2024/02/Blue-White-Gradient-Instagram--2--1.png",
    "publishedAt": "2023-12-04T15:01:45.000+01:00",
    "updatedAt": "2024-02-11T10:38:46.000+01:00",
    "author": "Fernando Nikolic",
    "tags": [
      "Weekly Digest",
      "#Import 2025-12-30 07:22"
    ]
  },
  "narrative-shift": {
    "title": "Weekly Media Recap #20",
    "description": "This week's spotlight: CNBC",
    "image": "https://cms.perception.to/content/images/2024/02/Blue-White--1--1.png",
    "publishedAt": "2023-11-27T15:01:11.000+01:00",
    "updatedAt": "2024-02-11T10:38:17.000+01:00",
    "author": "Fernando Nikolic",
    "tags": [
      "Weekly Digest",
      "#Import 2025-12-30 07:22"
    ]
  },
  "what-journalists-are-beginning-to": {
    "title": "Weekly Media Recap #19",
    "description": "What Journalists Are Beginning To Notice.",
    "image": "https://cms.perception.to/content/images/2024/02/Blue-White--1--2.png",
    "publishedAt": "2023-11-20T15:01:02.000+01:00",
    "updatedAt": "2024-02-11T10:37:47.000+01:00",
    "author": "Fernando Nikolic",
    "tags": [
      "Weekly Digest",
      "#Import 2025-12-30 07:22"
    ]
  },
  "it-feels-like-2016-again": {
    "title": "Weekly Media Recap #18",
    "description": "It Feels Like 2016 Again",
    "image": "https://cms.perception.to/content/images/2024/02/Blue-White--3--1.png",
    "publishedAt": "2023-11-13T15:00:41.000+01:00",
    "updatedAt": "2024-02-11T10:37:23.000+01:00",
    "author": "Fernando Nikolic",
    "tags": [
      "Weekly Digest",
      "#Import 2025-12-30 07:22"
    ]
  },
  "institutions-are-coming-but-they": {
    "title": "Weekly Media Recap #17",
    "description": "Institutions Are Coming, But They Are... Regulatory?",
    "image": "https://cms.perception.to/content/images/2024/02/Blue-White-2.png",
    "publishedAt": "2023-11-06T15:01:15.000+01:00",
    "updatedAt": "2024-02-11T10:37:05.000+01:00",
    "author": "Fernando Nikolic",
    "tags": [
      "Weekly Digest",
      "#Import 2025-12-30 07:22"
    ]
  },
  "feeling-bullish-yet": {
    "title": "Weekly Media Recap #16",
    "description": "Feeling Bullish Yet?",
    "image": "https://cms.perception.to/content/images/2024/02/Blue-White-Gradient-Instagram-3.png",
    "publishedAt": "2023-10-23T15:01:14.000+02:00",
    "updatedAt": "2024-02-11T10:36:36.000+01:00",
    "author": "Fernando Nikolic",
    "tags": [
      "Weekly Digest",
      "#Import 2025-12-30 07:22"
    ]
  },
  "the-new-york-times-sets-the-stage": {
    "title": "Weekly Media Recap #15",
    "description": "The New York Times Sets the Stage for Fear Mongering",
    "image": "https://cms.perception.to/content/images/2024/02/Blue-White-Gradient-Instagram--2--3.png",
    "publishedAt": "2023-10-16T15:01:45.000+02:00",
    "updatedAt": "2024-02-11T10:35:58.000+01:00",
    "author": "Fernando Nikolic",
    "tags": [
      "Weekly Digest",
      "#Import 2025-12-30 07:22"
    ]
  },
  "sbf-trial-and-how-legal-circuses": {
    "title": "Weekly Media Recap #14",
    "description": "SBF Trial And How Legal Circuses Affect The Perception Of The Public And Regulators",
    "image": "https://cms.perception.to/content/images/2024/02/Blue-White-3.png",
    "publishedAt": "2023-10-09T15:00:53.000+02:00",
    "updatedAt": "2024-02-11T10:35:31.000+01:00",
    "author": "Fernando Nikolic",
    "tags": [
      "Weekly Digest",
      "#Import 2025-12-30 07:22"
    ]
  },
  "the-ultimate-test-for-the-bitcoin": {
    "title": "Weekly Media Recap #13",
    "description": "The \"Ultimate Test\" For The Bitcoin Mining Industry Is Coming",
    "image": "https://cms.perception.to/content/images/2024/02/Blue-White--1--3.png",
    "publishedAt": "2023-10-02T15:02:18.000+02:00",
    "updatedAt": "2024-02-09T09:27:43.000+01:00",
    "author": "Fernando Nikolic",
    "tags": [
      "Weekly Digest",
      "#Import 2025-12-30 07:22"
    ]
  },
  "bitcoins-fed-nightmare": {
    "title": "Weekly Media Recap #12",
    "description": "\"Bitcoin's Fed Nightmare\"",
    "image": "https://cms.perception.to/content/images/2024/02/Blue-White-Gradient-Instagram-5.png",
    "publishedAt": "2023-09-25T15:00:35.000+02:00",
    "updatedAt": "2024-02-09T09:28:18.000+01:00",
    "author": "Fernando Nikolic",
    "tags": [
      "Weekly Digest",
      "#Import 2025-12-30 07:22"
    ]
  },
  "kill-the-noise-mainstream-medias": {
    "title": "Weekly Media Recap #11",
    "description": "Kill the Noise: Mainstream Media's Rush to Sensationalism",
    "image": "https://cms.perception.to/content/images/2024/02/Blue-White-Gradient-Instagram--1-.png",
    "publishedAt": "2023-09-18T15:00:10.000+02:00",
    "updatedAt": "2024-02-10T11:25:54.000+01:00",
    "author": "Fernando Nikolic",
    "tags": [
      "Weekly Digest",
      "#Import 2025-12-30 07:22"
    ]
  },
  "bitcoin-miners-navigate-power-shortages": {
    "title": "Weekly Media Recap #10",
    "description": "Bitcoin Miners Navigate Power Shortages and Policy Shifts",
    "image": "https://cms.perception.to/content/images/2024/02/Blue-White-Gradient.png",
    "publishedAt": "2023-09-11T15:12:15.000+02:00",
    "updatedAt": "2024-02-09T09:32:44.000+01:00",
    "author": "Fernando Nikolic",
    "tags": [
      "Weekly Digest",
      "#Import 2025-12-30 07:22"
    ]
  },
  "forbes-is-letting-you-know-oman-is": {
    "title": "Weekly Media Recap #9",
    "description": "Forbes Is Letting You Know: Oman Is Coming For Your Hash Rate",
    "image": "https://cms.perception.to/content/images/2024/02/Blue-White-4.png",
    "publishedAt": "2023-08-28T11:09:36.000+02:00",
    "updatedAt": "2024-02-09T09:32:53.000+01:00",
    "author": "Fernando Nikolic",
    "tags": [
      "Weekly Digest",
      "#Import 2025-12-30 07:22"
    ]
  },
  "reporters-begged-for-drama-and-volatility": {
    "title": "Weekly Media Recap #8",
    "description": "Reporters Begged for Drama, and Volatility Delivered",
    "image": "https://cms.perception.to/content/images/2024/02/Blue-White--3--3.png",
    "publishedAt": "2023-08-21T00:24:49.000+02:00",
    "updatedAt": "2024-02-09T09:33:09.000+01:00",
    "author": "Fernando Nikolic",
    "tags": [
      "Weekly Digest",
      "#Import 2025-12-30 07:22"
    ]
  },
  "new-york-times-capitulates-says-bitcoin": {
    "title": "Weekly Media Recap #7",
    "description": "Scams surface, anticipation around SEC's Bitcoin ETF decision, mining giants' robust strategies in tumultuous times, and the New York Times offers a balanced...",
    "image": "https://cms.perception.to/content/images/2024/02/Blue-White-Gradient-Instagram-6.png",
    "publishedAt": "2023-08-14T12:11:47.000+02:00",
    "updatedAt": "2024-02-11T10:34:37.000+01:00",
    "author": "Fernando Nikolic",
    "tags": [
      "Weekly Digest",
      "#Import 2025-12-30 07:22"
    ]
  },
  "michael-saylor-does-a-press-round": {
    "title": "Weekly Media Recap #6",
    "description": "BBC, Fox, and Newsweek delve into the darker side of Bitcoin, while Bitcoin's significant role in the financial market is underscored by Bloomberg and CNBC.",
    "image": "https://cms.perception.to/content/images/2024/02/Blue-White--3--4.png",
    "publishedAt": "2023-08-07T11:58:09.000+02:00",
    "updatedAt": "2024-02-09T09:34:21.000+01:00",
    "author": "Fernando Nikolic",
    "tags": [
      "Weekly Digest",
      "#Import 2025-12-30 07:22"
    ]
  },
  "gary-gensler-brian-armstrong-coinbase": {
    "title": "Weekly Media Recap #5",
    "description": "Cybercrime, Scandal, and a Game-Changing Revelation from Newsweek!",
    "image": "https://cms.perception.to/content/images/2024/02/Blue-White--1--4.png",
    "publishedAt": "2023-07-31T10:59:18.000+02:00",
    "updatedAt": "2024-02-09T09:35:06.000+01:00",
    "author": "Fernando Nikolic",
    "tags": [
      "Weekly Digest",
      "#Import 2025-12-30 07:22"
    ]
  },
  "skyrocketing-mining-difficulty-sparks": {
    "title": "Weekly Media Recap #4",
    "description": "Skyrocketing Mining Difficulty Sparks A Surge In Discussions.",
    "image": "https://cms.perception.to/content/images/2024/02/Blue-White-Gradient-Instagram-7.png",
    "publishedAt": "2023-07-25T17:07:01.000+02:00",
    "updatedAt": "2024-02-09T09:35:52.000+01:00",
    "author": "Fernando Nikolic",
    "tags": [
      "Weekly Digest",
      "#Import 2025-12-30 07:22"
    ]
  },
  "rfk-jr-is-either-a-visionary-pioneer": {
    "title": "Weekly Media Recap #3",
    "description": "Amidst the negative coverage of El Salvador's President and Bitfinex hacks, RFK Jr.'s advocacy for Bitcoin stands out.",
    "image": "https://cms.perception.to/content/images/2024/02/Blue-White-Gradient-Instagram-4.png",
    "publishedAt": "2023-07-23T19:15:16.000+02:00",
    "updatedAt": "2024-02-09T09:36:28.000+01:00",
    "author": "Fernando Nikolic",
    "tags": [
      "Weekly Digest",
      "#Import 2025-12-30 07:22"
    ]
  },
  "bitcoin-mining-wins-on-twitter-despite": {
    "title": "Weekly Media Recap #2",
    "description": "A social media snapshot of the Bitcoin Mining space in the past week.",
    "image": "https://cms.perception.to/content/images/2024/02/Blue-White--1--5.png",
    "publishedAt": "2023-07-19T12:34:29.000+02:00",
    "updatedAt": "2024-02-09T09:36:57.000+01:00",
    "author": "Fernando Nikolic",
    "tags": [
      "Weekly Digest",
      "#Import 2025-12-30 07:22"
    ]
  },
  "bitcoin-in-the-news-week-28": {
    "title": "Weekly Media Recap #1",
    "description": "RFK Jr.'s holdings, Standard Chartered's bold prediction, Europe's first Bitcoin ETF. Plus, get a glimpse into the future with POLITICO's coverage on the ris...",
    "image": "https://cms.perception.to/content/images/2024/02/Blue-White--3--2.png",
    "publishedAt": "2023-07-17T16:01:41.000+02:00",
    "updatedAt": "2024-02-11T10:33:27.000+01:00",
    "author": "Fernando Nikolic",
    "tags": [
      "Weekly Digest",
      "#Import 2025-12-30 07:22"
    ]
  },
  "the-inexplicable-embrace-of-craig": {
    "title": "The Inexplicable Embrace of Craig Wright as Satoshi Nakamoto: An Op...",
    "description": "How the media, in a quest for sensationalism, perpetuates the dubious narrative of Craig Wright as Bitcoin's creator, Satoshi Nakamoto.",
    "image": "https://cms.perception.to/content/images/2024/02/Craig-Wright-Forbes.jpeg",
    "publishedAt": "2023-07-13T22:14:46.000+02:00",
    "updatedAt": "2024-04-27T22:26:58.000+02:00",
    "author": "Fernando Nikolic",
    "tags": [
      "Opinion",
      "#Import 2025-12-30 07:22"
    ]
  }
};

export const DEFAULT_RESEARCH_IMAGE = 'https://perception.to/social-images/pages/bitcoin-media-research.png';
