steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/payload-cms:$COMMIT_SHA'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/payload-cms:$COMMIT_SHA'
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'payload-cms'
      - '--image'
      - 'gcr.io/$PROJECT_ID/payload-cms:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'
      - '--set-env-vars'
      - 'MONGODB_URI=mongodb+srv://fernikolic:3IPN6DQAOj9XVIHg@cluster0.1gtyyut.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0,PAYLOAD_SECRET=3aef0141d27e0d436dcb0134a441b021f124bbe1063e0f3b43933d563b8ad911'

images:
  - 'gcr.io/$PROJECT_ID/payload-cms:$COMMIT_SHA' 