name: Update Crypto Events

on:
  schedule:
    # Runs every Sunday at 6 AM UTC
    - cron: '0 6 * * 0'
  workflow_dispatch:  # Allows manual triggering only by repo owner
    inputs:
      reason:
        description: 'Reason for manual trigger'
        required: true
        type: string

# Restrict permissions for security
permissions:
  contents: write  # Only for pushing updates
  actions: read

jobs:
  update-events:
    runs-on: ubuntu-latest

    # Only run if triggered by schedule or by repository owner
    if: github.event_name == 'schedule' || github.actor == github.repository_owner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Fetch crypto events
      run: python scripts/fetch-events.py
      env:
        PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}

    - name: Create Pull Request with updated events
      run: |
        # Check if there are changes
        git add data/events.json
        if git diff --staged --quiet; then
          echo "No changes to commit"
          exit 0
        fi

        # Create a new branch for the update
        BRANCH_NAME="auto-update-$(date +%Y%m%d-%H%M%S)"
        git checkout -b $BRANCH_NAME

        # Commit changes
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "🔄 Weekly crypto events update - $(date +%Y-%m-%d)

        Updated conference data from Perplexity API search:
        - Comprehensive search across major crypto conferences
        - Filtered for events from Sept 2024 - Dec 2025
        - Includes Bitcoin, DeFi, Web3, stablecoin, and enterprise events

        Auto-generated by GitHub Actions"

        # Push the branch
        git push -u origin $BRANCH_NAME

        # Create pull request
        gh pr create \
          --title "🔄 Auto-update: Crypto Events $(date +%Y-%m-%d)" \
          --body "**Automated crypto conference data update**

        This PR contains the latest cryptocurrency and blockchain conference data fetched from Perplexity API.

        ## Changes:
        - Updated \`data/events.json\` with comprehensive conference listings
        - Covers events from September 2024 through December 2025
        - Includes major conferences worldwide (Bitcoin, DeFi, Web3, stablecoins)

        ## Review Notes:
        - Data is automatically validated for future dates only
        - Events include registration URLs, pricing, and descriptions
        - Categories and locations are automatically extracted

        **🤖 This PR was automatically created by GitHub Actions**" \
          --head $BRANCH_NAME \
          --base main
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}